"""Wikipedia page titles for places whose name alone does not resolve."""
OVERRIDE = {
    "Joe's Pizza": "Joe's Pizza", "Junior's": "Junior's", "Sylvia's": "Sylvia's Restaurant of Harlem",
    "Russ & Daughters": "Russ & Daughters", "Lombardi's": "Lombardi's", "Rao's": "Rao's",
    "Red Rooster": "Red Rooster (restaurant)", "Veselka": "Veselka", "Balthazar": "Balthazar (restaurant)",
    "Shake Shack Madison Square Park": "Shake Shack", "Chelsea Market": "Chelsea Market",
    "Zabar's": "Zabar's", "Levain Bakery": "Levain Bakery", "Magnolia Bakery": "Magnolia Bakery",
    "Gray's Papaya": "Gray's Papaya", "Delmonico's": "Delmonico's", "The Battery": "The Battery (Manhattan)",
    "Brooklyn Bridge": "Brooklyn Bridge", "Times Square": "Times Square", "Union Square": "Union Square, Manhattan",
    "Columbus Circle": "Columbus Circle", "City Hall": "New York City Hall", "Lincoln Center": "Lincoln Center",
    "Low Memorial Library": "Low Memorial Library", "The Vessel": "Vessel (structure)",
    "Manhattan Bridge Arch": "Manhattan Bridge", "South Street Seaport": "South Street Seaport",
    "Staten Island Ferry Terminal": "Whitehall Terminal", "Astor Place Cube": "Alamo (sculpture)",
    "Gramercy Park": "Gramercy Park", "Roosevelt Island Tramway": "Roosevelt Island Tramway",
    "Javits Center": "Jacob K. Javits Convention Center", "The Dakota": "The Dakota",
    "Strawberry Fields": "Strawberry Fields (memorial)", "The Plaza Hotel": "Plaza Hotel",
    "Harlem Meer": "Harlem Meer", "Audubon Ballroom": "Audubon Ballroom", "Shepard Hall": "Shepard Hall",
    "Ghostbusters Firehouse": "Hook & Ladder 8", "Hotel Chelsea": "Hotel Chelsea",
    "Macy's Herald Square": "Macy's Herald Square", "Williamsburg Bridge": "Williamsburg Bridge",
    "George Washington Bridge": "George Washington Bridge", "Little Red Lighthouse": "Jeffrey's Hook Light",
    "Hamilton Grange": "Hamilton Grange National Memorial", "Bethesda Terrace": "Bethesda Terrace and Fountain",
    "Charging Bull": "Charging Bull", "Grant's Tomb": "Grant's Tomb", "Apollo Theater": "Apollo Theater",
    "Metropolitan Museum of Art": "Metropolitan Museum of Art", "Museum of Modern Art": "Museum of Modern Art",
    "Intrepid Museum": "Intrepid Museum", "New York Public Library": "New York Public Library Main Branch",
    "9/11 Memorial & Museum": "National September 11 Memorial & Museum", "Tenement Museum": "Lower East Side Tenement Museum",
    "The Met Cloisters": "The Cloisters", "Cooper Hewitt": "Cooper Hewitt, Smithsonian Design Museum",
    "Hispanic Society Museum": "Hispanic Society of America", "Strand Bookstore": "Strand Bookstore",
    "Jefferson Market Library": "Jefferson Market Library", "Central Park Zoo": "Central Park Zoo",
    "The High Line": "High Line", "Little Island": "Little Island at Pier 55", "Bryant Park": "Bryant Park",
    "Fort Tryon Park": "Fort Tryon Park", "Sheep Meadow": "Sheep Meadow", "Conservatory Garden": "Conservatory Garden",
    "Highbridge Water Tower": "Highbridge Water Tower", "Paley Park": "Paley Park", "Rockefeller Park": "Rockefeller Park",
    "The Great Lawn": "Great Lawn and Turtle Pond", "Alice in Wonderland Statue": "Alice in Wonderland (sculpture)",
    "Fearless Girl": "Fearless Girl", "Cleopatra's Needle": "Cleopatra's Needle (New York City)",
    "St. Paul's Chapel": "St. Paul's Chapel", "Woolworth Building": "Woolworth Building",
    "African Burial Ground": "African Burial Ground National Monument", "Irish Hunger Memorial": "Irish Hunger Memorial",
    "Duke Ellington Memorial": "Duke Ellington Memorial", "LOVE Sculpture": "Love (Indiana)",
    "Tiffany & Co. Fifth Avenue": "Tiffany & Co. Building", "The Ansonia": "The Ansonia",
    "Cooper Union Foundation Building": "Cooper Union Foundation Building", "Temple Emanu-El": "Congregation Emanu-El of New York",
    "Federal Hall": "Federal Hall", "Castle Clinton": "Castle Clinton", "Sherman Monument": "William Tecumseh Sherman Monument",
    "Trinity Church": "Trinity Church (Manhattan)", "Bow Bridge": "Bow Bridge", "Soldiers' and Sailors' Monument": "Soldiers' and Sailors' Monument (Manhattan)",
    "Eldridge Street Synagogue": "Eldridge Street Synagogue", "Madison Square Garden": "Madison Square Garden",
    "Carnegie Hall": "Carnegie Hall", "Gracie Mansion": "Gracie Mansion", "Morris-Jumel Mansion": "Morris–Jumel Mansion",
    "Dyckman Farmhouse": "Dyckman House", "Old St. Patrick's Cathedral": "Basilica of St. Patrick's Old Cathedral",
    "St. Patrick's Cathedral": "St. Patrick's Cathedral (Manhattan)", "Belvedere Castle": "Belvedere Castle",
    "Port Authority Bus Terminal": "Port Authority Bus Terminal", "Stonewall Inn": "Stonewall Inn",
    "Katz's Delicatessen": "Katz's Delicatessen", "Tavern on the Green": "Tavern on the Green",
    "Nom Wah Tea Parlor": "Nom Wah Tea Parlor", "Ferrara Bakery": "Ferrara Bakery and Cafe",
    "Keens Steakhouse": "Keens Steakhouse", "Minetta Tavern": "Minetta Tavern", "Fraunces Tavern": "Fraunces Tavern",
    "Barney Greengrass": "Barney Greengrass", "Serendipity 3": "Serendipity 3", "Dominique Ansel Bakery": "Dominique Ansel",
    "Pete's Tavern": "Pete's Tavern", "P.J. Clarke's": "P. J. Clarke's", "Mamoun's Falafel": "Mamoun's",
    "Whitney Museum of American Art": "Whitney Museum", "The Frick Collection": "Frick Collection",
    "Studio Museum in Harlem": "Studio Museum in Harlem", "New Museum": "New Museum",
    "The Morgan Library & Museum": "Morgan Library & Museum", "New-York Historical Society": "New-York Historical Society",
    "Museum of Jewish Heritage": "Museum of Jewish Heritage", "Merchant's House Museum": "Merchant's House Museum",
    "The Jewish Museum": "Jewish Museum (Manhattan)", "Madison Square Park": "Madison Square and Madison Square Park",
    "Tompkins Square Park": "Tompkins Square Park", "Inwood Hill Park": "Inwood Hill Park", "Marcus Garvey Park": "Marcus Garvey Park",
    "Morningside Park": "Morningside Park (Manhattan)", "Seward Park": "Seward Park (Manhattan)", "Columbus Park": "Columbus Park (Manhattan)",
    "Stuyvesant Square": "Stuyvesant Square", "St. Nicholas Park": "St. Nicholas Park", "Sara D. Roosevelt Park": "Sara D. Roosevelt Park",
    "Museum of the City of New York": "Museum of the City of New York", "Neue Galerie": "Neue Galerie New York",
    # boroughs
    "Brooklyn Borough Hall": "Brooklyn Borough Hall", "Barclays Center": "Barclays Center", "Jane's Carousel": "Jane's Carousel",
    "Brooklyn Heights Promenade": "Brooklyn Heights Promenade", "Brooklyn Navy Yard": "Brooklyn Navy Yard", "Domino Park": "Domino Park",
    "Fort Greene Park": "Fort Greene Park", "Grand Army Plaza": "Grand Army Plaza", "Pratt Institute": "Pratt Institute",
    "Williamsburg Bridge (Brooklyn)": "Williamsburg Bridge", "Gowanus Canal": "Gowanus Canal", "McCarren Park": "McCarren Park",
    "DUMBO Archway": "Dumbo, Brooklyn", "Juliana's Pizza": "Juliana's Pizza", "Peter Luger Steak House": "Peter Luger Steak House",
    "Junior's Restaurant": "Junior's", "Lucali": "Lucali", "Sahadi's": "Sahadi's", "Time Out Market New York": "Empire Stores",
    "Brooklyn Brewery": "Brooklyn Brewery", "Brooklyn Museum": "Brooklyn Museum", "Brooklyn Academy of Music": "Brooklyn Academy of Music",
    "New York Transit Museum": "New York Transit Museum", "Center for Brooklyn History": "Center for Brooklyn History",
    "St. Ann's Warehouse": "St. Ann's Warehouse", "Brooklyn Botanic Garden": "Brooklyn Botanic Garden", "Cobble Hill Park": "Cobble Hill Park",
    "Commodore Barry Park": "Commodore Barry Park", "Cadman Plaza Park": "Cadman Plaza", "Williamsburgh Savings Bank Tower": "Williamsburgh Savings Bank Tower",
    "Old Stone House": "Old Stone House (Brooklyn)", "Plymouth Church": "Plymouth Church of the Pilgrims", "Clock Tower Building": "Clock Tower Building (Brooklyn)",
    "Gantry Plaza State Park": "Gantry Plaza State Park", "Queensboro Plaza": "Queensboro Plaza station", "Silvercup Studios": "Silvercup Studios",
    "One Court Square": "One Court Square", "Astoria Park": "Astoria Park", "Kaufman Astoria Studios": "Kaufman Astoria Studios",
    "Queensbridge Park": "Queensbridge Park", "Steinway Street": "Steinway Street", "LaGuardia Community College": "LaGuardia Community College",
    "Hunters Point Library": "Hunters Point Library", "Bohemian Hall & Beer Garden": "Bohemian Hall and Beer Garden", "Taverna Kyclades": "Taverna Kyclades",
    "Elias Corner": "Elias Corner", "Court Square Diner": "Court Square Diner", "MoMA PS1": "MoMA PS1", "Museum of the Moving Image": "Museum of the Moving Image",
    "Noguchi Museum": "Noguchi Museum", "SculptureCenter": "SculptureCenter", "Socrates Sculpture Park": "Socrates Sculpture Park", "Rainey Park": "Rainey Park",
    "Hunters Point South Park": "Hunter's Point South Park", "Athens Square": "Athens Square Park", "Pepsi-Cola Sign": "Pepsi-Cola sign",
    "Hell Gate Bridge": "Hell Gate Bridge", "Queensboro Bridge": "Queensboro Bridge",
    "Yankee Stadium": "Yankee Stadium", "Bronx County Courthouse": "Bronx County Courthouse", "Andrew Freedman Home": "Andrew Freedman Home",
    "The Hub": "The Hub, Bronx", "Hostos Community College": "Hostos Community College", "Bronx Terminal Market": "Bronx Terminal Market",
    "St. Mary's Park": "St. Mary's Park (Bronx)", "Crotona Park": "Crotona Park", "Claremont Park": "Claremont Park",
    "Arthur Avenue Retail Market": "Arthur Avenue", "Yankee Tavern": "Yankee Tavern", "Bronx Museum of the Arts": "Bronx Museum of the Arts",
    "Edgar Allan Poe Cottage": "Edgar Allan Poe Cottage", "Bronx Zoo": "Bronx Zoo", "New York Botanical Garden": "New York Botanical Garden",
    "Franz Sigel Park": "Franz Sigel Park", "Joyce Kilmer Park": "Joyce Kilmer Park", "1520 Sedgwick Avenue": "1520 Sedgwick Avenue",
    "Lorelei Fountain": "Lorelei Fountain", "Bronx General Post Office": "Bronx General Post Office", "Loew's Paradise Theater": "Paradise Theater (Bronx)",
    "St. George Terminal": "St. George Terminal", "Staten Island Borough Hall": "Staten Island Borough Hall", "Postcards": "Postcards (memorial)",
    "Snug Harbor Cultural Center": "Snug Harbor Cultural Center", "Wagner College": "Wagner College", "Silver Lake Park": "Silver Lake Park",
    "Tompkinsville Park": "Tompkinsville, Staten Island", "Fort Wadsworth": "Fort Wadsworth", "Enoteca Maria": "Enoteca Maria",
    "National Lighthouse Museum": "National Lighthouse Museum", "Staten Island Museum": "Staten Island Museum", "Alice Austen House": "Alice Austen House",
    "Staten Island Children's Museum": "Staten Island Children's Museum", "Garibaldi-Meucci Museum": "Garibaldi–Meucci Museum",
    "Staten Island Zoo": "Staten Island Zoo", "Clove Lakes Park": "Clove Lakes Park", "Von Briesen Park": "Von Briesen Park",
    "Richmond County Bank Ballpark": "Richmond County Bank Ballpark", "St. George Theatre": "St. George Theatre",
}
