"""Wikipedia page titles for places whose name alone does not resolve."""
OVERRIDE = {
    "Joe's Pizza": "Joe's Pizza", "Junior's": "Junior's", "Sylvia's": "Sylvia's Restaurant of Harlem",
    "Russ & Daughters": "Russ & Daughters", "Lombardi's": "Lombardi's", "Rao's": "Rao's",
    "Red Rooster": "Red Rooster (restaurant)", "Veselka": "Veselka", "Balthazar": "Balthazar (restaurant)",
    "Shake Shack Madison Square Park": "Shake Shack", "Chelsea Market": "Chelsea Market",
    "Zabar's": "Zabar's", "Levain Bakery": "Levain Bakery", "Magnolia Bakery": "Magnolia Bakery",
    "Gray's Papaya": "Gray's Papaya", "Delmonico's": "Delmonico's", "The Battery": "The Battery (Manhattan)",
    "Brooklyn Bridge": "Brooklyn Bridge", "Times Square": "Times Square", "Union Square": "Union Square, Manhattan",
    "Columbus Circle": "Columbus Circle", "City Hall": "New York City Hall", "Lincoln Center": "Lincoln Center",
    "Low Memorial Library": "Low Memorial Library", "The Vessel": "Vessel (structure)",
    "Manhattan Bridge Arch": "Manhattan Bridge", "South Street Seaport": "South Street Seaport",
    "Staten Island Ferry Terminal": "Whitehall Terminal", "Astor Place Cube": "Alamo (sculpture)",
    "Gramercy Park": "Gramercy Park", "Roosevelt Island Tramway": "Roosevelt Island Tramway",
    "Javits Center": "Jacob K. Javits Convention Center", "The Dakota": "The Dakota",
    "Strawberry Fields": "Strawberry Fields (memorial)", "The Plaza Hotel": "Plaza Hotel",
    "Harlem Meer": "Harlem Meer", "Audubon Ballroom": "Audubon Ballroom", "Shepard Hall": "Shepard Hall",
    "Ghostbusters Firehouse": "Hook & Ladder 8", "Hotel Chelsea": "Hotel Chelsea",
    "Macy's Herald Square": "Macy's Herald Square", "Williamsburg Bridge": "Williamsburg Bridge",
    "George Washington Bridge": "George Washington Bridge", "Little Red Lighthouse": "Jeffrey's Hook Light",
    "Hamilton Grange": "Hamilton Grange National Memorial", "Bethesda Terrace": "Bethesda Terrace and Fountain",
    "Charging Bull": "Charging Bull", "Grant's Tomb": "Grant's Tomb", "Apollo Theater": "Apollo Theater",
    "Metropolitan Museum of Art": "Metropolitan Museum of Art", "Museum of Modern Art": "Museum of Modern Art",
    "Intrepid Museum": "Intrepid Museum", "New York Public Library": "New York Public Library Main Branch",
    "9/11 Memorial & Museum": "National September 11 Memorial & Museum", "Tenement Museum": "Lower East Side Tenement Museum",
    "The Met Cloisters": "The Cloisters", "Cooper Hewitt": "Cooper Hewitt, Smithsonian Design Museum",
    "Hispanic Society Museum": "Hispanic Society of America", "Strand Bookstore": "Strand Bookstore",
    "Jefferson Market Library": "Jefferson Market Library", "Central Park Zoo": "Central Park Zoo",
    "The High Line": "High Line", "Little Island": "Little Island at Pier 55", "Bryant Park": "Bryant Park",
    "Fort Tryon Park": "Fort Tryon Park", "Sheep Meadow": "Sheep Meadow", "Conservatory Garden": "Conservatory Garden",
    "Highbridge Water Tower": "Highbridge Water Tower", "Paley Park": "Paley Park", "Rockefeller Park": "Rockefeller Park",
    "The Great Lawn": "Great Lawn and Turtle Pond", "Alice in Wonderland Statue": "Alice in Wonderland (sculpture)",
    "Fearless Girl": "Fearless Girl", "Cleopatra's Needle": "Cleopatra's Needle (New York City)",
    "St. Paul's Chapel": "St. Paul's Chapel", "Woolworth Building": "Woolworth Building",
    "African Burial Ground": "African Burial Ground National Monument", "Irish Hunger Memorial": "Irish Hunger Memorial",
    "Duke Ellington Memorial": "Duke Ellington Memorial", "LOVE Sculpture": "Love (Indiana)",
    "Tiffany & Co. Fifth Avenue": "Tiffany & Co. Building", "The Ansonia": "The Ansonia",
    "Cooper Union Foundation Building": "Cooper Union Foundation Building", "Temple Emanu-El": "Congregation Emanu-El of New York",
    "Federal Hall": "Federal Hall", "Castle Clinton": "Castle Clinton", "Sherman Monument": "William Tecumseh Sherman Monument",
    "Trinity Church": "Trinity Church (Manhattan)", "Bow Bridge": "Bow Bridge", "Soldiers' and Sailors' Monument": "Soldiers' and Sailors' Monument (Manhattan)",
    "Eldridge Street Synagogue": "Eldridge Street Synagogue", "Madison Square Garden": "Madison Square Garden",
    "Carnegie Hall": "Carnegie Hall", "Gracie Mansion": "Gracie Mansion", "Morris-Jumel Mansion": "Morris–Jumel Mansion",
    "Dyckman Farmhouse": "Dyckman House", "Old St. Patrick's Cathedral": "Basilica of St. Patrick's Old Cathedral",
    "St. Patrick's Cathedral": "St. Patrick's Cathedral (Manhattan)", "Belvedere Castle": "Belvedere Castle",
    "Port Authority Bus Terminal": "Port Authority Bus Terminal", "Stonewall Inn": "Stonewall Inn",
    "Katz's Delicatessen": "Katz's Delicatessen", "Tavern on the Green": "Tavern on the Green",
    "Nom Wah Tea Parlor": "Nom Wah Tea Parlor", "Ferrara Bakery": "Ferrara Bakery and Cafe",
    "Keens Steakhouse": "Keens Steakhouse", "Minetta Tavern": "Minetta Tavern", "Fraunces Tavern": "Fraunces Tavern",
    "Barney Greengrass": "Barney Greengrass", "Serendipity 3": "Serendipity 3", "Dominique Ansel Bakery": "Dominique Ansel",
    "Pete's Tavern": "Pete's Tavern", "P.J. Clarke's": "P. J. Clarke's", "Mamoun's Falafel": "Mamoun's",
    "Whitney Museum of American Art": "Whitney Museum", "The Frick Collection": "Frick Collection",
    "Studio Museum in Harlem": "Studio Museum in Harlem", "New Museum": "New Museum",
    "The Morgan Library & Museum": "Morgan Library & Museum", "New-York Historical Society": "New-York Historical Society",
    "Museum of Jewish Heritage": "Museum of Jewish Heritage", "Merchant's House Museum": "Merchant's House Museum",
    "The Jewish Museum": "Jewish Museum (Manhattan)", "Madison Square Park": "Madison Square and Madison Square Park",
    "Tompkins Square Park": "Tompkins Square Park", "Inwood Hill Park": "Inwood Hill Park", "Marcus Garvey Park": "Marcus Garvey Park",
    "Morningside Park": "Morningside Park (Manhattan)", "Seward Park": "Seward Park (Manhattan)", "Columbus Park": "Columbus Park (Manhattan)",
    "Stuyvesant Square": "Stuyvesant Square", "St. Nicholas Park": "St. Nicholas Park", "Sara D. Roosevelt Park": "Sara D. Roosevelt Park",
    "Museum of the City of New York": "Museum of the City of New York", "Neue Galerie": "Neue Galerie New York",
}
